
version: "3.8"
services:
  order:
    build: ./order
    ports:
      - "50051:50051"
  payment:
    build: ./payment
    ports:
      - "50052:50052"
  shipping:
    build: ./shipping
    ports:
      - "50053:50053"
